#!/usr/bin/bash

# Generates a new self signed certificate and private key.
# Based on: https://www.adamintech.com/openssl-how-to-generate-a-self-signed-certificate-and-key-with-elliptic-curves/

# Generate new private key
# Curve prime256v1 seems to be secure: https://security.stackexchange.com/questions/78621/which-elliptic-curve-should-i-use
openssl ecparam -name prime256v1 -genkey -out dts.key

# The certificate is valid for 10 years.
openssl req -new -x509 -key dts.key -sha256 -nodes -out dts.crt -days 3650 -utf8 -subj "/C=DE/ST=Baden-Württemberg/L=Böblingen/O=AP Sensing/OU=R&D/CN=$(hostname).local"
