#!/usr/bin/bash

# This script makes sure '/usr/lib/group' and '/etc/group' are in sync for the 'dts-cert' group.
# This is a workaround since rpm-ostree currently does not properly support systemd-sysusers.
# Refs:
# https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_unable_to_add_user_to_group
# https://github.com/coreos/rpm-ostree/issues/49

# Remove all existing occurrences of 'dts-cert' from the groups list
sed -i '/^dts-cert:/d' /etc/group
# Update it with the latest line
grep "dts-cert:" /usr/lib/group >> /etc/group
# Make sure the 'dts' and 'nginx' users are inside the 'dts-cert' group 
systemd-sysusers --inline "m dts dts-cert"
systemd-sysusers --inline "m nginx dts-cert"

echo "Success!"